-- MySQL Script generated by MySQL Workbench
-- Wed Jan 19 14:23:50 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema RandomConnectionSOl
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `RandomConnectionSOl` ;

-- -----------------------------------------------------
-- Schema RandomConnectionSOl
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `RandomConnectionSOl` DEFAULT CHARACTER SET utf8 ;
USE `RandomConnectionSOl` ;

-- -----------------------------------------------------
-- Table `RandomConnectionSOl`.`major`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RandomConnectionSOl`.`major` (
  `major_id` INT NOT NULL AUTO_INCREMENT,
  `major_name` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`major_id`),
  UNIQUE INDEX `id_UNIQUE` (`major_id` ASC) VISIBLE,
  UNIQUE INDEX `name_UNIQUE` (`major_name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RandomConnectionSOl`.`students`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RandomConnectionSOl`.`students` (
  `student_id` CHAR(8) NOT NULL,
  `passward` VARCHAR(20) NOT NULL,
  `nickname` VARCHAR(20) NOT NULL,
  `birth` DATE NOT NULL,
  `gender` CHAR(1) BINARY NOT NULL,
  `major_id` INT NULL,
  `place` VARCHAR(10) NOT NULL,
  `MBTI` CHAR(4) NULL,
  `hobby` VARCHAR(20) NULL,
  `use_time` INT UNSIGNED NOT NULL DEFAULT 0,
  `is_online` TINYINT NOT NULL DEFAULT 0,
  UNIQUE INDEX `id_UNIQUE` (`student_id` ASC) VISIBLE,
  PRIMARY KEY (`student_id`),
  INDEX `major_id_idx` (`major_id` ASC) VISIBLE,
  UNIQUE INDEX `nickname_UNIQUE` (`nickname` ASC) VISIBLE,
  CONSTRAINT `student_major`
    FOREIGN KEY (`major_id`)
    REFERENCES `RandomConnectionSOl`.`major` (`major_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RandomConnectionSOl`.`interest`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RandomConnectionSOl`.`interest` (
  `interest_id` INT NOT NULL AUTO_INCREMENT,
  `interest_name` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`interest_id`),
  UNIQUE INDEX `interest_id_UNIQUE` (`interest_id` ASC) VISIBLE,
  UNIQUE INDEX `name_UNIQUE` (`interest_name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RandomConnectionSOl`.`student_interest`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RandomConnectionSOl`.`student_interest` (
  `student_interest_id` INT NOT NULL AUTO_INCREMENT,
  `interest_id` INT NOT NULL,
  `student_id` CHAR(8) NOT NULL,
  INDEX `interest_id_idx` (`interest_id` ASC) INVISIBLE,
  PRIMARY KEY (`student_interest_id`),
  UNIQUE INDEX `student_interest_id_UNIQUE` (`student_interest_id` ASC) VISIBLE,
  CONSTRAINT `student_to_interest`
    FOREIGN KEY (`student_id`)
    REFERENCES `RandomConnectionSOl`.`students` (`student_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `interest_to_interest`
    FOREIGN KEY (`interest_id`)
    REFERENCES `RandomConnectionSOl`.`interest` (`interest_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RandomConnectionSOl`.`conversation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RandomConnectionSOl`.`conversation` (
  `conversation_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `student_1_id` CHAR(8) NOT NULL,
  `student_2_id` CHAR(8) NOT NULL,
  `student_1_text` LONGTEXT NULL,
  `student_2_text` LONGTEXT NULL,
  `start_time` DATETIME NOT NULL,
  `end_time` DATETIME NULL,
  PRIMARY KEY (`conversation_id`),
  UNIQUE INDEX `id_UNIQUE` (`conversation_id` ASC) VISIBLE,
  INDEX `conversation_index` (`student_1_id` ASC) VISIBLE,
  INDEX `conversation_student_2_idx` (`student_2_id` ASC) VISIBLE,
  CONSTRAINT `conversation_student_1`
    FOREIGN KEY (`student_1_id`)
    REFERENCES `RandomConnectionSOl`.`students` (`student_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `conversation_student_2`
    FOREIGN KEY (`student_2_id`)
    REFERENCES `RandomConnectionSOl`.`students` (`student_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RandomConnectionSOl`.`room`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RandomConnectionSOl`.`room` (
  `major_id` INT NOT NULL,
  `capacity` INT NOT NULL,
  PRIMARY KEY (`major_id`),
  UNIQUE INDEX `major_id_UNIQUE` (`major_id` ASC) VISIBLE,
  CONSTRAINT `major_room`
    FOREIGN KEY (`major_id`)
    REFERENCES `RandomConnectionSOl`.`major` (`major_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RandomConnectionSOl`.`score`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RandomConnectionSOl`.`score` (
  `from_student_id` CHAR(8) NOT NULL,
  `to_student_id` CHAR(8) NOT NULL,
  `score` INT NOT NULL,
  PRIMARY KEY (`from_student_id`, `to_student_id`),
  UNIQUE INDEX `from_student_id_UNIQUE` (`from_student_id` ASC) VISIBLE,
  UNIQUE INDEX `to_student_id_UNIQUE` (`to_student_id` ASC) VISIBLE,
  CONSTRAINT `student_1_score`
    FOREIGN KEY (`from_student_id`)
    REFERENCES `RandomConnectionSOl`.`students` (`student_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `student_2_score`
    FOREIGN KEY (`to_student_id`)
    REFERENCES `RandomConnectionSOl`.`students` (`student_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RandomConnectionSOl`.`friend`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RandomConnectionSOl`.`friend` (
  `from_student_id` CHAR(8) NOT NULL,
  `to_student_id` CHAR(8) NOT NULL,
  PRIMARY KEY (`from_student_id`, `to_student_id`),
  UNIQUE INDEX `from_student_id_UNIQUE` (`from_student_id` ASC) VISIBLE,
  UNIQUE INDEX `to_student_id_UNIQUE` (`to_student_id` ASC) VISIBLE,
  CONSTRAINT `from_student_friend`
    FOREIGN KEY (`from_student_id`)
    REFERENCES `RandomConnectionSOl`.`students` (`student_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `to_student_friend`
    FOREIGN KEY (`to_student_id`)
    REFERENCES `RandomConnectionSOl`.`students` (`student_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

# Create View

CREATE VIEW `mbti_score` AS SELECT o.mbti_one, mbti as mbti_two, AVG(o.score) as mu_score FROM (SELECT from_student_id, mbti as mbti_one, to_student_id, score
        FROM score, students WHERE from_student_id = students.student_id) as o , students WHERE o.to_student_id = students.student_id
        GROUP BY mbti_one, mbti_two;
